# Need to run this chunk of code before calling "runApp"
path <- "/Users/patrick/Library/CloudStorage/Dropbox/Chenbo PhD folder/Impact Metric Study/Kathmandu"
setwd(path)
require(tidyverse)
require(dplyr)
require(haven)
require(glmnet)
require(ggplot2)
require(ggpubr)
require(scales)
require(labelled)
require(caret)
require(pROC)
require(ROCR)
require(tree)
require(randomForest)
require(smotefamily)
require(splitTools)
require(boot)
require(readxl)
require(writexl)
require(PRROC)
require(doParallel)
require(tictoc)
require(report)
require(pwr)
require(pwrss)
require(shiny)
# Load data that are preprocessed to be in the required format
load("clean_Data.RData")
# Call the "runApp" command to access the GUI of web applications
runApp("CompareDIMs")
runApp("RankDIMs")
